#!/bin/bash
#
# https://stackoverflow.com/questions/50690526/how-to-publish-binary-python-wheels-for-linux-on-a-local-machine
#
XNAME=quay.io/pypa/manylinux_2_28_x86_64

xrm(){
    docker rmi ${XNAME}
}

xpull(){
    docker pull ${XNAME}
}

xbuild(){
docker run \
    -i \
    -t \
    --rm \
    -v `pwd`:/io \
    ${XNAME} \
    /io/build-wheels.sh
}

$*
