#!/bin/bash
if [ ! -d build ]; then
    mkdir build
fi
pushd build
cmake \
    $* \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DLITEHTML_BUILD_TESTING=OFF \
    -DLITEHTMLPY_BUILD_TESTING=ON \
    -DLITEHTMLPY_INCLUDE_CAIRO_CONTAINERS=ON \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=Debug \
    ..
popd
