#!/bin/bash
#
# https://stackoverflow.com/questions/50690526/how-to-publish-binary-python-wheels-for-linux-on-a-local-machine
#
XIMAGE=quay.io/pypa/manylinux_2_17_x86_64
XNAME=manylinux

xrm(){
    docker rmi ${XIMAGE}
}

xpull(){
    docker pull ${XIMAGE}
}

xbuild(){
docker run \
    -i \
    -t \
    --rm \
    -v `pwd`:/io \
    ${XIMAGE} \
    /io/build-wheels.sh
}

$*
