#!/bin/bash
rm -rf __pycache__ build CMakeFiles litehtmlpy.egg-info wheelhouse litehtmlpy/__pycache__
rm -f .ninja_deps .ninja_log build.ninja cmake_install.cmake CMakeCache.txt
rm -rf litehtml pybind11
mkdir litehtml
mkdir pybind11
git submodule deinit --all -f
git submodule update --init
