    py::class_<lh::css_length>(m, "css_length")
        .def(py::init<>())
        .def(py::init<float, lh::css_units>())
		//css_length& operator=(float val)
        .def("is_predefined", &lh::css_length::is_predefined)
        //.def("predef", &lh::css_length::predef)
        .def("predef_value", &lh::css_length::predef_value)
        .def("set_value", &lh::css_length::set_value)
        .def("val", &lh::css_length::val)
        .def("units", &lh::css_length::units)
        .def("calc_percent", &lh::css_length::calc_percent)
        .def("to_string", &lh::css_length::to_string)
	;
