    py::enum_<lh::document_mode>(m, "document_mode", py::arithmetic())
        .value("no_quirks_mode", lh::document_mode::no_quirks_mode)
        .value("quirks_mode", lh::document_mode::quirks_mode)
        .value("limited_quirks_mode", lh::document_mode::limited_quirks_mode)
        .export_values()
    ;
    py::enum_<lh::text_decoration_line>(m, "text_decoration_line", py::arithmetic())
        .value("text_decoration_line_none", lh::text_decoration_line::text_decoration_line_none)
        .value("text_decoration_line_underline", lh::text_decoration_line::text_decoration_line_underline)
        .value("text_decoration_line_overline", lh::text_decoration_line::text_decoration_line_overline)
        .value("text_decoration_line_line_through", lh::text_decoration_line::text_decoration_line_line_through)
        .export_values()
    ;
    py::enum_<lh::text_decoration_style>(m, "text_decoration_style", py::arithmetic())
        .value("text_decoration_style_solid", lh::text_decoration_style::text_decoration_style_solid)
        .value("text_decoration_style_double", lh::text_decoration_style::text_decoration_style_double)
        .value("text_decoration_style_dotted", lh::text_decoration_style::text_decoration_style_dotted)
        .value("text_decoration_style_dashed", lh::text_decoration_style::text_decoration_style_dashed)
        .value("text_decoration_style_wavy", lh::text_decoration_style::text_decoration_style_wavy)
        .value("text_decoration_style_max", lh::text_decoration_style::text_decoration_style_max)
        .export_values()
    ;
    py::enum_<lh::text_decoration_thickness>(m, "text_decoration_thickness", py::arithmetic())
        .value("text_decoration_thickness_auto", lh::text_decoration_thickness::text_decoration_thickness_auto)
        .value("text_decoration_thickness_from_font", lh::text_decoration_thickness::text_decoration_thickness_from_font)
        .export_values()
    ;
    py::enum_<lh::text_emphasis_position>(m, "text_emphasis_position", py::arithmetic())
        .value("text_emphasis_position_over", lh::text_emphasis_position::text_emphasis_position_over)
        .value("text_emphasis_position_under", lh::text_emphasis_position::text_emphasis_position_under)
        .value("text_emphasis_position_left", lh::text_emphasis_position::text_emphasis_position_left)
        .value("text_emphasis_position_right", lh::text_emphasis_position::text_emphasis_position_right)
        .export_values()
    ;
    py::enum_<lh::draw_flag>(m, "draw_flag", py::arithmetic())
        .value("draw_root", lh::draw_flag::draw_root)
        .value("draw_block", lh::draw_flag::draw_block)
        .value("draw_floats", lh::draw_flag::draw_floats)
        .value("draw_inlines", lh::draw_flag::draw_inlines)
        .value("draw_positioned", lh::draw_flag::draw_positioned)
        .export_values()
    ;
    py::enum_<lh::style_display>(m, "style_display", py::arithmetic())
        .value("display_none", lh::style_display::display_none)
        .value("display_block", lh::style_display::display_block)
        .value("display_inline", lh::style_display::display_inline)
        .value("display_inline_block", lh::style_display::display_inline_block)
        .value("display_inline_table", lh::style_display::display_inline_table)
        .value("display_list_item", lh::style_display::display_list_item)
        .value("display_table", lh::style_display::display_table)
        .value("display_table_caption", lh::style_display::display_table_caption)
        .value("display_table_cell", lh::style_display::display_table_cell)
        .value("display_table_column", lh::style_display::display_table_column)
        .value("display_table_column_group", lh::style_display::display_table_column_group)
        .value("display_table_footer_group", lh::style_display::display_table_footer_group)
        .value("display_table_header_group", lh::style_display::display_table_header_group)
        .value("display_table_row", lh::style_display::display_table_row)
        .value("display_table_row_group", lh::style_display::display_table_row_group)
        .value("display_inline_text", lh::style_display::display_inline_text)
        .value("display_flex", lh::style_display::display_flex)
        .value("display_inline_flex", lh::style_display::display_inline_flex)
        .export_values()
    ;
    py::enum_<lh::font_size>(m, "font_size", py::arithmetic())
        .value("font_size_xx_small", lh::font_size::font_size_xx_small)
        .value("font_size_x_small", lh::font_size::font_size_x_small)
        .value("font_size_small", lh::font_size::font_size_small)
        .value("font_size_medium", lh::font_size::font_size_medium)
        .value("font_size_large", lh::font_size::font_size_large)
        .value("font_size_x_large", lh::font_size::font_size_x_large)
        .value("font_size_xx_large", lh::font_size::font_size_xx_large)
        .value("font_size_smaller", lh::font_size::font_size_smaller)
        .value("font_size_larger", lh::font_size::font_size_larger)
        .export_values()
    ;
    py::enum_<lh::line_height>(m, "line_height", py::arithmetic())
        .value("line_height_normal", lh::line_height::line_height_normal)
        .export_values()
    ;
    py::enum_<lh::font_style>(m, "font_style", py::arithmetic())
        .value("font_style_normal", lh::font_style::font_style_normal)
        .value("font_style_italic", lh::font_style::font_style_italic)
        .export_values()
    ;
    py::enum_<lh::font_variant>(m, "font_variant", py::arithmetic())
        .value("font_variant_normal", lh::font_variant::font_variant_normal)
        .value("font_variant_small_caps", lh::font_variant::font_variant_small_caps)
        .export_values()
    ;
    py::enum_<lh::font_weight>(m, "font_weight", py::arithmetic())
        .value("font_weight_normal", lh::font_weight::font_weight_normal)
        .value("font_weight_bold", lh::font_weight::font_weight_bold)
        .value("font_weight_bolder", lh::font_weight::font_weight_bolder)
        .value("font_weight_lighter", lh::font_weight::font_weight_lighter)
        .export_values()
    ;
    py::enum_<lh::list_style_type>(m, "list_style_type", py::arithmetic())
        .value("list_style_type_none", lh::list_style_type::list_style_type_none)
        .value("list_style_type_circle", lh::list_style_type::list_style_type_circle)
        .value("list_style_type_disc", lh::list_style_type::list_style_type_disc)
        .value("list_style_type_square", lh::list_style_type::list_style_type_square)
        .value("list_style_type_armenian", lh::list_style_type::list_style_type_armenian)
        .value("list_style_type_cjk_ideographic", lh::list_style_type::list_style_type_cjk_ideographic)
        .value("list_style_type_decimal", lh::list_style_type::list_style_type_decimal)
        .value("list_style_type_decimal_leading_zero", lh::list_style_type::list_style_type_decimal_leading_zero)
        .value("list_style_type_georgian", lh::list_style_type::list_style_type_georgian)
        .value("list_style_type_hebrew", lh::list_style_type::list_style_type_hebrew)
        .value("list_style_type_hiragana", lh::list_style_type::list_style_type_hiragana)
        .value("list_style_type_hiragana_iroha", lh::list_style_type::list_style_type_hiragana_iroha)
        .value("list_style_type_katakana", lh::list_style_type::list_style_type_katakana)
        .value("list_style_type_katakana_iroha", lh::list_style_type::list_style_type_katakana_iroha)
        .value("list_style_type_lower_alpha", lh::list_style_type::list_style_type_lower_alpha)
        .value("list_style_type_lower_greek", lh::list_style_type::list_style_type_lower_greek)
        .value("list_style_type_lower_latin", lh::list_style_type::list_style_type_lower_latin)
        .value("list_style_type_lower_roman", lh::list_style_type::list_style_type_lower_roman)
        .value("list_style_type_upper_alpha", lh::list_style_type::list_style_type_upper_alpha)
        .value("list_style_type_upper_latin", lh::list_style_type::list_style_type_upper_latin)
        .value("list_style_type_upper_roman", lh::list_style_type::list_style_type_upper_roman)
        .export_values()
    ;
    py::enum_<lh::list_style_position>(m, "list_style_position", py::arithmetic())
        .value("list_style_position_inside", lh::list_style_position::list_style_position_inside)
        .value("list_style_position_outside", lh::list_style_position::list_style_position_outside)
        .export_values()
    ;
    py::enum_<lh::vertical_align>(m, "vertical_align", py::arithmetic())
        .value("va_baseline", lh::vertical_align::va_baseline)
        .value("va_sub", lh::vertical_align::va_sub)
        .value("va_super", lh::vertical_align::va_super)
        .value("va_top", lh::vertical_align::va_top)
        .value("va_text_top", lh::vertical_align::va_text_top)
        .value("va_middle", lh::vertical_align::va_middle)
        .value("va_bottom", lh::vertical_align::va_bottom)
        .value("va_text_bottom", lh::vertical_align::va_text_bottom)
        .export_values()
    ;
    py::enum_<lh::border_width>(m, "border_width", py::arithmetic())
        .value("border_width_thin", lh::border_width::border_width_thin)
        .value("border_width_medium", lh::border_width::border_width_medium)
        .value("border_width_thick", lh::border_width::border_width_thick)
        .export_values()
    ;
    py::enum_<lh::border_style>(m, "border_style", py::arithmetic())
        .value("border_style_none", lh::border_style::border_style_none)
        .value("border_style_hidden", lh::border_style::border_style_hidden)
        .value("border_style_dotted", lh::border_style::border_style_dotted)
        .value("border_style_dashed", lh::border_style::border_style_dashed)
        .value("border_style_solid", lh::border_style::border_style_solid)
        .value("border_style_double", lh::border_style::border_style_double)
        .value("border_style_groove", lh::border_style::border_style_groove)
        .value("border_style_ridge", lh::border_style::border_style_ridge)
        .value("border_style_inset", lh::border_style::border_style_inset)
        .value("border_style_outset", lh::border_style::border_style_outset)
        .export_values()
    ;
    py::enum_<lh::element_float>(m, "element_float", py::arithmetic())
        .value("float_none", lh::element_float::float_none)
        .value("float_left", lh::element_float::float_left)
        .value("float_right", lh::element_float::float_right)
        .export_values()
    ;
    py::enum_<lh::element_clear>(m, "element_clear", py::arithmetic())
        .value("clear_none", lh::element_clear::clear_none)
        .value("clear_left", lh::element_clear::clear_left)
        .value("clear_right", lh::element_clear::clear_right)
        .value("clear_both", lh::element_clear::clear_both)
        .export_values()
    ;
    py::enum_<lh::css_units>(m, "css_units", py::arithmetic())
        .value("css_units_none", lh::css_units::css_units_none)
        .value("css_units_percentage", lh::css_units::css_units_percentage)
        .value("css_units_in", lh::css_units::css_units_in)
        .value("css_units_cm", lh::css_units::css_units_cm)
        .value("css_units_mm", lh::css_units::css_units_mm)
        .value("css_units_em", lh::css_units::css_units_em)
        .value("css_units_ex", lh::css_units::css_units_ex)
        .value("css_units_pt", lh::css_units::css_units_pt)
        .value("css_units_pc", lh::css_units::css_units_pc)
        .value("css_units_px", lh::css_units::css_units_px)
        .value("css_units_vw", lh::css_units::css_units_vw)
        .value("css_units_vh", lh::css_units::css_units_vh)
        .value("css_units_vmin", lh::css_units::css_units_vmin)
        .value("css_units_vmax", lh::css_units::css_units_vmax)
        .value("css_units_rem", lh::css_units::css_units_rem)
        .value("css_units_ch", lh::css_units::css_units_ch)
        .export_values()
    ;
    py::enum_<lh::background_attachment>(m, "background_attachment", py::arithmetic())
        .value("background_attachment_scroll", lh::background_attachment::background_attachment_scroll)
        .value("background_attachment_fixed", lh::background_attachment::background_attachment_fixed)
        .export_values()
    ;
    py::enum_<lh::background_repeat>(m, "background_repeat", py::arithmetic())
        .value("background_repeat_repeat", lh::background_repeat::background_repeat_repeat)
        .value("background_repeat_repeat_x", lh::background_repeat::background_repeat_repeat_x)
        .value("background_repeat_repeat_y", lh::background_repeat::background_repeat_repeat_y)
        .value("background_repeat_no_repeat", lh::background_repeat::background_repeat_no_repeat)
        .export_values()
    ;
    py::enum_<lh::background_box>(m, "background_box", py::arithmetic())
        .value("background_box_border", lh::background_box::background_box_border)
        .value("background_box_padding", lh::background_box::background_box_padding)
        .value("background_box_content", lh::background_box::background_box_content)
        .export_values()
    ;
    py::enum_<lh::background_position>(m, "background_position", py::arithmetic())
        .value("background_position_left", lh::background_position::background_position_left)
        .value("background_position_right", lh::background_position::background_position_right)
        .value("background_position_top", lh::background_position::background_position_top)
        .value("background_position_bottom", lh::background_position::background_position_bottom)
        .value("background_position_center", lh::background_position::background_position_center)
        .export_values()
    ;
    py::enum_<lh::element_position>(m, "element_position", py::arithmetic())
        .value("element_position_static", lh::element_position::element_position_static)
        .value("element_position_relative", lh::element_position::element_position_relative)
        .value("element_position_absolute", lh::element_position::element_position_absolute)
        .value("element_position_fixed", lh::element_position::element_position_fixed)
        .export_values()
    ;
    py::enum_<lh::text_align>(m, "text_align", py::arithmetic())
        .value("text_align_left", lh::text_align::text_align_left)
        .value("text_align_right", lh::text_align::text_align_right)
        .value("text_align_center", lh::text_align::text_align_center)
        .value("text_align_justify", lh::text_align::text_align_justify)
        .export_values()
    ;
    py::enum_<lh::text_transform>(m, "text_transform", py::arithmetic())
        .value("text_transform_none", lh::text_transform::text_transform_none)
        .value("text_transform_capitalize", lh::text_transform::text_transform_capitalize)
        .value("text_transform_uppercase", lh::text_transform::text_transform_uppercase)
        .value("text_transform_lowercase", lh::text_transform::text_transform_lowercase)
        .export_values()
    ;
    py::enum_<lh::white_space>(m, "white_space", py::arithmetic())
        .value("white_space_normal", lh::white_space::white_space_normal)
        .value("white_space_nowrap", lh::white_space::white_space_nowrap)
        .value("white_space_pre", lh::white_space::white_space_pre)
        .value("white_space_pre_line", lh::white_space::white_space_pre_line)
        .value("white_space_pre_wrap", lh::white_space::white_space_pre_wrap)
        .export_values()
    ;
    py::enum_<lh::overflow>(m, "overflow", py::arithmetic())
        .value("overflow_visible", lh::overflow::overflow_visible)
        .value("overflow_hidden", lh::overflow::overflow_hidden)
        .value("overflow_scroll", lh::overflow::overflow_scroll)
        .value("overflow_auto", lh::overflow::overflow_auto)
        .value("overflow_no_display", lh::overflow::overflow_no_display)
        .value("overflow_no_content", lh::overflow::overflow_no_content)
        .export_values()
    ;
    py::enum_<lh::background_size>(m, "background_size", py::arithmetic())
        .value("background_size_auto", lh::background_size::background_size_auto)
        .value("background_size_cover", lh::background_size::background_size_cover)
        .value("background_size_contain", lh::background_size::background_size_contain)
        .export_values()
    ;
    py::enum_<lh::visibility>(m, "visibility", py::arithmetic())
        .value("visibility_visible", lh::visibility::visibility_visible)
        .value("visibility_hidden", lh::visibility::visibility_hidden)
        .value("visibility_collapse", lh::visibility::visibility_collapse)
        .export_values()
    ;
    py::enum_<lh::border_collapse>(m, "border_collapse", py::arithmetic())
        .value("border_collapse_collapse", lh::border_collapse::border_collapse_collapse)
        .value("border_collapse_separate", lh::border_collapse::border_collapse_separate)
        .export_values()
    ;
    py::enum_<lh::content_property>(m, "content_property", py::arithmetic())
        .value("content_property_none", lh::content_property::content_property_none)
        .value("content_property_normal", lh::content_property::content_property_normal)
        .value("content_property_open_quote", lh::content_property::content_property_open_quote)
        .value("content_property_close_quote", lh::content_property::content_property_close_quote)
        .value("content_property_no_open_quote", lh::content_property::content_property_no_open_quote)
        .value("content_property_no_close_quote", lh::content_property::content_property_no_close_quote)
        .export_values()
    ;
    py::enum_<lh::select_result>(m, "select_result", py::arithmetic())
        .value("select_no_match", lh::select_result::select_no_match)
        .value("select_match", lh::select_result::select_match)
        .value("select_match_pseudo_class", lh::select_result::select_match_pseudo_class)
        .value("select_match_with_before", lh::select_result::select_match_with_before)
        .value("select_match_with_after", lh::select_result::select_match_with_after)
        .export_values()
    ;
    py::enum_<lh::appearance>(m, "appearance", py::arithmetic())
        .value("appearance_none", lh::appearance::appearance_none)
        .value("appearance_auto", lh::appearance::appearance_auto)
        .value("appearance_menulist_button", lh::appearance::appearance_menulist_button)
        .value("appearance_textfield", lh::appearance::appearance_textfield)
        .value("appearance_button", lh::appearance::appearance_button)
        .value("appearance_checkbox", lh::appearance::appearance_checkbox)
        .value("appearance_listbox", lh::appearance::appearance_listbox)
        .value("appearance_menulist", lh::appearance::appearance_menulist)
        .value("appearance_meter", lh::appearance::appearance_meter)
        .value("appearance_progress_bar", lh::appearance::appearance_progress_bar)
        .value("appearance_push_button", lh::appearance::appearance_push_button)
        .value("appearance_radio", lh::appearance::appearance_radio)
        .value("appearance_searchfield", lh::appearance::appearance_searchfield)
        .value("appearance_slider_horizontal", lh::appearance::appearance_slider_horizontal)
        .value("appearance_square_button", lh::appearance::appearance_square_button)
        .value("appearance_textarea", lh::appearance::appearance_textarea)
        .export_values()
    ;
    py::enum_<lh::box_sizing>(m, "box_sizing", py::arithmetic())
        .value("box_sizing_content_box", lh::box_sizing::box_sizing_content_box)
        .value("box_sizing_border_box", lh::box_sizing::box_sizing_border_box)
        .export_values()
    ;
    py::enum_<lh::media_type>(m, "media_type", py::arithmetic())
        .value("media_type_unknown", lh::media_type::media_type_unknown)
        .value("media_type_all", lh::media_type::media_type_all)
        .value("media_type_print", lh::media_type::media_type_print)
        .value("media_type_screen", lh::media_type::media_type_screen)
        .value("media_type_first_deprecated", lh::media_type::media_type_first_deprecated)
        .export_values()
    ;
    py::enum_<lh::render_type>(m, "render_type", py::arithmetic())
        .value("render_all", lh::render_type::render_all)
        .value("render_no_fixed", lh::render_type::render_no_fixed)
        .value("render_fixed_only", lh::render_type::render_fixed_only)
        .export_values()
    ;
    py::enum_<lh::flex_direction>(m, "flex_direction", py::arithmetic())
        .value("flex_direction_row", lh::flex_direction::flex_direction_row)
        .value("flex_direction_row_reverse", lh::flex_direction::flex_direction_row_reverse)
        .value("flex_direction_column", lh::flex_direction::flex_direction_column)
        .value("flex_direction_column_reverse", lh::flex_direction::flex_direction_column_reverse)
        .export_values()
    ;
    py::enum_<lh::flex_wrap>(m, "flex_wrap", py::arithmetic())
        .value("flex_wrap_nowrap", lh::flex_wrap::flex_wrap_nowrap)
        .value("flex_wrap_wrap", lh::flex_wrap::flex_wrap_wrap)
        .value("flex_wrap_wrap_reverse", lh::flex_wrap::flex_wrap_wrap_reverse)
        .export_values()
    ;
    py::enum_<lh::flex_justify_content>(m, "flex_justify_content", py::arithmetic())
        .value("flex_justify_content_normal", lh::flex_justify_content::flex_justify_content_normal)
        .value("flex_justify_content_flex_start", lh::flex_justify_content::flex_justify_content_flex_start)
        .value("flex_justify_content_flex_end", lh::flex_justify_content::flex_justify_content_flex_end)
        .value("flex_justify_content_center", lh::flex_justify_content::flex_justify_content_center)
        .value("flex_justify_content_space_between", lh::flex_justify_content::flex_justify_content_space_between)
        .value("flex_justify_content_space_around", lh::flex_justify_content::flex_justify_content_space_around)
        .value("flex_justify_content_start", lh::flex_justify_content::flex_justify_content_start)
        .value("flex_justify_content_end", lh::flex_justify_content::flex_justify_content_end)
        .value("flex_justify_content_left", lh::flex_justify_content::flex_justify_content_left)
        .value("flex_justify_content_right", lh::flex_justify_content::flex_justify_content_right)
        .value("flex_justify_content_space_evenly", lh::flex_justify_content::flex_justify_content_space_evenly)
        .value("flex_justify_content_stretch", lh::flex_justify_content::flex_justify_content_stretch)
        .export_values()
    ;
    py::enum_<lh::flex_align_items>(m, "flex_align_items", py::arithmetic())
        .value("flex_align_items_auto", lh::flex_align_items::flex_align_items_auto)
        .value("flex_align_items_normal", lh::flex_align_items::flex_align_items_normal)
        .value("flex_align_items_stretch", lh::flex_align_items::flex_align_items_stretch)
        .value("flex_align_items_baseline", lh::flex_align_items::flex_align_items_baseline)
        .value("flex_align_items_center", lh::flex_align_items::flex_align_items_center)
        .value("flex_align_items_start", lh::flex_align_items::flex_align_items_start)
        .value("flex_align_items_end", lh::flex_align_items::flex_align_items_end)
        .value("flex_align_items_self_start", lh::flex_align_items::flex_align_items_self_start)
        .value("flex_align_items_self_end", lh::flex_align_items::flex_align_items_self_end)
        .value("flex_align_items_flex_start", lh::flex_align_items::flex_align_items_flex_start)
        .value("flex_align_items_flex_end", lh::flex_align_items::flex_align_items_flex_end)
        .value("flex_align_items_first", lh::flex_align_items::flex_align_items_first)
        .value("flex_align_items_last", lh::flex_align_items::flex_align_items_last)
        .value("flex_align_items_unsafe", lh::flex_align_items::flex_align_items_unsafe)
        .value("flex_align_items_safe", lh::flex_align_items::flex_align_items_safe)
        .export_values()
    ;
    py::enum_<lh::flex_align_content>(m, "flex_align_content", py::arithmetic())
        .value("flex_align_content_flex_start", lh::flex_align_content::flex_align_content_flex_start)
        .value("flex_align_content_start", lh::flex_align_content::flex_align_content_start)
        .value("flex_align_content_flex_end", lh::flex_align_content::flex_align_content_flex_end)
        .value("flex_align_content_end", lh::flex_align_content::flex_align_content_end)
        .value("flex_align_content_center", lh::flex_align_content::flex_align_content_center)
        .value("flex_align_content_space_between", lh::flex_align_content::flex_align_content_space_between)
        .value("flex_align_content_space_around", lh::flex_align_content::flex_align_content_space_around)
        .value("flex_align_content_stretch", lh::flex_align_content::flex_align_content_stretch)
        .export_values()
    ;
    py::enum_<lh::flex_basis>(m, "flex_basis", py::arithmetic())
        .value("flex_basis_auto", lh::flex_basis::flex_basis_auto)
        .value("flex_basis_content", lh::flex_basis::flex_basis_content)
        .value("flex_basis_fit_content", lh::flex_basis::flex_basis_fit_content)
        .value("flex_basis_min_content", lh::flex_basis::flex_basis_min_content)
        .value("flex_basis_max_content", lh::flex_basis::flex_basis_max_content)
        .export_values()
    ;
    py::enum_<lh::caption_side>(m, "caption_side", py::arithmetic())
        .value("caption_side_top", lh::caption_side::caption_side_top)
        .value("caption_side_bottom", lh::caption_side::caption_side_bottom)
        .export_values()
    ;
